// <auto-generated />
using System;
using AIStudyHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIStudyHub.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260712210000_AddTrashBinShareLevelRecommendationTokenWalletLapses")]
    partial class AddTrashBinShareLevelRecommendationTokenWalletLapses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIStudyHub.Data.Entities.DocumentShare", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasColumnName("share_id");
                    b.Property<Guid>("DocumentId").HasColumnType("uniqueidentifier").HasColumnName("doc_id");
                    b.Property<string>("Level").IsRequired().HasMaxLength(10).HasColumnType("nvarchar(10)").HasColumnName("level");
                    b.Property<Guid>("SharedBy").HasColumnType("uniqueidentifier").HasColumnName("shared_by");
                    b.Property<DateTime>("SharedAt").HasColumnType("datetime").HasColumnName("shared_at");
                    b.Property<Guid>("UserId").HasColumnType("uniqueidentifier").HasColumnName("u_id");
                    b.HasKey("Id");
                    b.HasIndex("DocumentId", "UserId").IsUnique();
                    b.HasIndex("UserId");
                    b.ToTable("DocumentShare", (string)null);
                });

            modelBuilder.Entity("AIStudyHub.Data.Entities.TokenLedger", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasColumnName("ledger_id");
                    b.Property<int>("EstimatedTokens").HasColumnType("int").HasColumnName("estimated_tokens");
                    b.Property<string>("FailureReason").HasMaxLength(500).HasColumnType("nvarchar(500)").HasColumnName("failure_reason");
                    b.Property<int?>("ActualTokens").HasColumnType("int").HasColumnName("actual_tokens");
                    b.Property<DateTime?>("CreatedAt").HasColumnType("datetime").HasColumnName("create_at");
                    b.Property<string>("OperationType").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)").HasColumnName("operation_type");
                    b.Property<Guid?>("RelatedEntityId").HasColumnType("uniqueidentifier").HasColumnName("related_entity_id");
                    b.Property<int>("Status").HasColumnType("int").HasColumnName("status");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime").HasColumnName("update_at");
                    b.Property<Guid>("UserId").HasColumnType("uniqueidentifier").HasColumnName("u_id");
                    b.HasKey("Id");
                    b.HasIndex("UserId");
                    b.HasIndex("UserId", "CreatedAt");
                    b.ToTable("TokenLedger", (string)null);
                });

            modelBuilder.Entity("AIStudyHub.Data.Entities.Recommendation", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier").HasColumnName("recommendation_id");
                    b.Property<string>("ActionUrl").HasMaxLength(500).HasColumnType("nvarchar(500)").HasColumnName("action_url");
                    b.Property<DateTime?>("CreatedAt").HasColumnType("datetime").HasColumnName("create_at");
                    b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)").HasColumnName("description");
                    b.Property<DateTime?>("DismissedAt").HasColumnType("datetime").HasColumnName("dismissed_at");
                    b.Property<Guid?>("ReferenceId").HasColumnType("uniqueidentifier").HasColumnName("reference_id");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Active").HasColumnName("status");
                    b.Property<string>("Title").IsRequired().HasMaxLength(255).HasColumnType("nvarchar(255)").HasColumnName("title");
                    b.Property<int>("Type").HasColumnType("int").HasColumnName("type");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime").HasColumnName("update_at");
                    b.Property<Guid>("UserId").HasColumnType("uniqueidentifier").HasColumnName("u_id");
                    b.HasKey("Id");
                    b.HasIndex("UserId", "Status");
                    b.ToTable("Recommendations", (string)null);
                });

            modelBuilder.Entity("AIStudyHub.Data.Entities.DocumentShare", b =>
                {
                    b.HasOne("AIStudyHub.Data.Entities.Document", "Document").WithMany("DocumentShares").HasForeignKey("DocumentId").OnDelete(DeleteBehavior.Cascade);
                    b.HasOne("AIStudyHub.Data.Entities.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AIStudyHub.Data.Entities.TokenLedger", b =>
                {
                    b.HasOne("AIStudyHub.Data.Entities.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AIStudyHub.Data.Entities.Recommendation", b =>
                {
                    b.HasOne("AIStudyHub.Data.Entities.User", "User").WithMany().HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AIStudyHub.Data.Entities.Document", b =>
            {
                b.Navigation("DocumentShares");
            });
#pragma warning restore 612, 618
        }
    }
}
